### ISSUE TITLE
SPAM emails

### ISSUE THREAD

**Issue by medikoo** [msavin/SteveJobs-meteor-jobs-queue#2]
Something is sending SPAM emails about this package.

They go to email addresses of accounts registered with Github.

It'll be great if that not happens

**Comment by skemb321** [comment]
hmmmm...I didn't know this. U subscribed via maxsavin's blog, no?

**Comment by medikoo** [comment]
No, I received email as below, and I don't remember subscribing to such "newsletters" anywhere

![screen shot 2017-10-24 at 17 11 48](https://user-images.githubusercontent.com/122434/31951643-06afe2c2-b8df-11e7-8671-375bc0b50c4d.png)

**Comment by msavin** [comment]
Hmm - thanks for letting me know - I will make sure to remove you from any/all newsletters.
