### ISSUE TITLE
Discussion: prioritizing jobs

### ISSUE THREAD

**Issue by msavin** [msavin/SteveJobs-meteor-jobs-queue#6]
Currently, the package runs jobs based on which is due the soonest. However, we might want to give some jobs priority over others. For example, if an application is sending out email newsletters over a queue, perhaps paying customers get to skip the wait.

There's three ways to implement this:
1- have a `expedite: true` field 
2- allow people to set arbitrary numbers for priority (ie. 1000, 900, 1)
3- have some kind of priority system (for example, numbers rated 1-10 have different effects)

I'm leaning on #1 for simplicity, or #2 for flexibility. I noticed some queue's have an approach like #3, but unless I am missing something, I do not see the benefit.

**Comment by luixal** [comment]
I think the third option it's quite useless too. The first may be too simple for many projects. I'd go with the second.

Also it seems easy to implement: just order the query for new jobs by that field?

**Comment by msavin** [comment]
The second is the winner, and indeed, quite easy to implement thanks to MongoDB.

**Comment by msavin** [comment]
Hmm, cool thing is we can also set negative numbers for priority to have it run after everything else
