### ISSUE TITLE
Use uid instead of Math.random()

### ISSUE THREAD

**Issue by hems** [msavin/SteveJobs-meteor-jobs-queue#8]
Using some simple UID will do a better job and it won't be risky as Math.random() ( :  

https://github.com/msavin/SteveJobs-meteor-jobs-queue/blob/2bd3278f5c489a196b95a3b82b44d33bc2856e37/package/server/control.js#L21

**Comment by msavin** [comment]
I don't think it's so risky, but I agree, its not a good practice. I switched it to Meteor's Random.id() function, coming in the next commit.

**Comment by hems** [comment]
I have had problems before caused by Math.random() generating the same number and it was the last thing i looked at hence why i'm raising the flag! also there are many things you can do to achieve "uuid" that would be more meaningful and useful when debugging, like timestamp + pid !

but that is obviously, just a small suggestion and more of a bar chat than a major problem here ( ;

**Comment by msavin** [comment]
Haha - that is crazy. Good to know :)

**Comment by hems** [comment]
yeah absolutely crazy! if you call Math.random() a lot of times in a row and count for the outputs you would be surprised! At least that's how it used to be, maybe things have changed ( ;
